"""submit message and session

Revision ID: 35ea2562119b
Revises: c5291063235f
Create Date: 2025-07-12 00:15:01.814606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35ea2562119b'
down_revision: Union[str, Sequence[str], None] = 'c5291063235f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('role', sa.String(length=20), nullable=False))
    op.drop_column('messages', 'sender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('messages', 'role')
    # ### end Alembic commands ###
