"""alter requirement data model

Revision ID: 5c8e535fe9e1
Revises: 3fc1589fbae5
Create Date: 2025-07-08 18:20:30.117738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8e535fe9e1'
down_revision: Union[str, Sequence[str], None] = '3fc1589fbae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('requirement_analysis', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'requirement_analysis')
    # ### end Alembic commands ###
