"""submit message and session

Revision ID: c5291063235f
Revises: 059d893360da
Create Date: 2025-07-12 00:12:32.515749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5291063235f'
down_revision: Union[str, Sequence[str], None] = '059d893360da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'session_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('sessions', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('sessions', 'session_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
